"""add field name and cel orders tables

Revision ID: 518ae5c96c1f
Revises: fb6ce28c532f
Create Date: 2024-09-15 22:47:01.810455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '518ae5c96c1f'
down_revision: Union[str, None] = 'fb6ce28c532f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('order', sa.Column('cel', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'cel')
    op.drop_column('order', 'name')
    # ### end Alembic commands ###
