"""refactor add not null field name and movil orders tables

Revision ID: 73fef376dc26
Revises: 518ae5c96c1f
Create Date: 2024-09-15 23:12:17.575424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73fef376dc26'
down_revision: Union[str, None] = '518ae5c96c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'movil',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'movil',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
