"""refactor model product tax and active

Revision ID: 96d1f094dff7
Revises: 22e020d0eefc
Create Date: 2024-09-08 20:42:01.118687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96d1f094dff7'
down_revision: Union[str, None] = '22e020d0eefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
