"""refactor tables

Revision ID: 9b8ec1ffaee9
Revises: 
Create Date: 2024-09-11 23:56:56.907075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b8ec1ffaee9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_detailsorder_product_id'), 'detailsorder', ['product_id'], unique=False)
    op.add_column('order', sa.Column('total_tax', sa.Numeric(), nullable=False))
    op.drop_column('order', 'total')
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('product', 'tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('product', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product', 'tax',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('order', sa.Column('total', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False))
    op.drop_column('order', 'total_tax')
    op.drop_index(op.f('ix_detailsorder_product_id'), table_name='detailsorder')
    op.alter_column('category', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
